# Goonstation Nightly Packager
# Based on Automaton
# Which is based on Turdis by Yogstation
# Wow. Runs every evening around 8pm eastern, before the coders start breaking shit.

name: Nightly

on:
  workflow_dispatch:
  schedule:
    - cron: '16 23 * * *'

jobs:
  nightly:
    name: Package
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        map: ["ATLAS", "DEVTEST"]
    steps:
      - uses: actions/checkout@v3
      # TODO: if running outside of goon, use an explicit reference to goonstation/goonstation

      - name: Cache BYOND
        uses: actions/cache@v3
        with:
          path: $HOME/BYOND
          key: ${{ runner.os }}-byond-${{ hashFiles('buildByond.conf')}}

      - name: Setup BYOND
        run: |
          tools/ci/install_byond.sh
          cd ${{github.workspace}}
          printenv
          echo "BYOND_SYSTEM=/home/runner/BYOND/byond" >> $GITHUB_ENV
          echo "/home/runner/BYOND/byond/bin" >> $GITHUB_PATH
          echo "LD_LIBRARY_PATH=/home/runner/BYOND/byond/bin:$LD_LIBRARY_PATH" >> $GITHUB_ENV
          echo "MANPATH=/home/runner/BYOND/byond/man:$MANPATH" >> $GITHUB_ENV
          touch +secret/__secret.dme

      - name: Compile map
        run: |
          tools/ci/dm.sh -DMAP_OVERRIDE_${{matrix.map}} goonstation.dme
      
      - name: Package
        run: |
          mkdir packaged
          mv goonstation.dmb goonstation.rsc sound strings assets LICENSE rust_g.dll ./packaged

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: GoonNightly${{matrix.map}}
          path: ${{github.workspace}}/packaged
